spring:
  application:
    name: zuul-service
  cloud:
    config:
      discovery:
        enabled: true
        service-id: ms-config-server

server:
  port: 8766

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true


